######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 15 17:44:37 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
